version: "3.9"
services:

  manager:
    container_name: manager
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: manager
        SERVICE_PORT: 8080
    environment:
      WORKER_ADDR: "http://worker-lb:7080"
      ALPHABET: "abcdefghijklmnopqrstuvwxyz1234567890"
      PART_COUNT: "16"
      TASK_TIMEOUT: "10M"
    ports:
      - "8080:8080"

  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: worker
    environment:
      MANAGER_ADDR: "http://manager:8080"
      TASK_TIMEOUT: "10M"
    healthcheck:
      test: curl -f http://localhost:8080/internal/healthcheck || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      replicas: 3
      # Uncomment the following lines to restict resourse consumption
      # resources:
      #   limits:
      #     cpus: '0.1'
      #     memory: 128M

  loadbalancer:
    container_name: worker-lb
    image: haproxy
    depends_on:
      worker:
        condition: service_healthy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "7080:7080"
